### PR TITLE
Add warioware story

### PR DESCRIPTION
**Pull request by chuckdries**
TODO: ask permission from @/mog before merging

[Click here](https://deploy-preview-3--cohost-storybook.netlify.app/?path=/story/posts-warioware--primary) to see the new story

### CODE REVIEW

**Comment by mogery** [comment]
LGTM, however, the fact that the UI says the post is by you is a tiny bit meh. I'm unfamiliar with how Storybook works at all, but it'd be cool if the example posts could have proper "attribution" that's visible outside of code as well.

**Comment by mogery** [comment]
oh, also, the reload button doesn't restart `failure.gif`

**Comment by mogery** [comment]
hmm, ok. so the post is actually broken in here, since the stock tailwind bounce animation doesn't seem to be present? anyways, you can polyfill it:

```
@keyframes bounce {
  0%, 100% {
    transform: translateY(-25%);
    animation-timing-function: cubic-bezier(0.8, 0, 1, 1);
  }
  50% {
    transform: translateY(0);
    animation-timing-function: cubic-bezier(0, 0, 0.2, 1);
  }
}
```

there is also an animation that is injected by the bug reporting widget, which some posts depend on, however i have not been able to find it.

**Comment by chuckdries** [comment]
@mogery thanks for the input! My solution is a little clunky, but I did figure out a way to let you specify who it looks like the post is from in the story

**Pull request merged**
